defmodule JiraathomeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :jiraathome

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_jiraathome_key",
    signing_salt: "+HCPgtn4",
    same_site: "Lax",
    max_age: 34_560_000,
    http_only: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :jiraathome,
    gzip: not code_reloading?,
    only: JiraathomeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :jiraathome
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.RewriteOn, [:x_forwarded_proto]
  plug :migrate_session_cookie
  plug Plug.Session, @session_options
  plug JiraathomeWeb.Router

  # Keep existing logins through the application rename; signatures and salts are unchanged.
  defp migrate_session_cookie(conn, _opts) do
    conn = Plug.Conn.fetch_cookies(conn)

    case {conn.req_cookies["_jiraathome_key"], conn.req_cookies["_pochetasks_key"]} do
      {nil, value} when is_binary(value) ->
        conn = %{
          conn
          | req_cookies: Map.put(conn.req_cookies, "_jiraathome_key", value),
            cookies: Map.put(conn.cookies, "_jiraathome_key", value)
        }

        conn
        |> Plug.Conn.put_resp_cookie("_jiraathome_key", value,
          max_age: 34_560_000,
          http_only: true,
          same_site: "Lax"
        )
        |> Plug.Conn.delete_resp_cookie("_pochetasks_key")

      _ ->
        conn
    end
  end
end
