defmodule Jiraathome.Repo.Migrations.AddCardPositions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :position, :float, null: false, default: 0.0
    end

    # Keep the existing newest-first order and give every card its own slot.
    execute "UPDATE cards SET position = -id"
  end

  def down do
    alter table(:cards) do
      remove :position
    end
  end
end
